export interface Symptom {
  id: number;
  name: string;
  description: string;
  possible_conditions: string[];
  home_remedies: string[];
  recommended_medicines: string[];
  when_to_see_doctor: string;
  severity: string;
}

export const symptoms: Symptom[] = [
  { id: 1, name: "Fever", description: "Elevated body temperature above 38°C", possible_conditions: ["Viral infection", "Flu", "Malaria", "Dengue", "COVID-19", "Typhoid"], home_remedies: ["Rest and stay hydrated", "Lukewarm sponge bath", "Ginger and honey tea", "Wet cloth on forehead"], recommended_medicines: ["Paracetamol", "Ibuprofen", "Aspirin"], when_to_see_doctor: "Fever above 39.4°C, lasting more than 3 days, or with severe headache/rash", severity: "moderate" },
  { id: 2, name: "Headache", description: "Pain or discomfort in the head, scalp, or neck", possible_conditions: ["Tension headache", "Migraine", "Sinus infection", "Hypertension", "Dehydration"], home_remedies: ["Rest in quiet dark room", "Stay hydrated", "Cold/warm compress", "Ginger tea", "Peppermint oil on temples"], recommended_medicines: ["Paracetamol", "Ibuprofen", "Aspirin", "Diclofenac"], when_to_see_doctor: "Sudden severe headache, with fever/stiff neck, or persistent despite treatment", severity: "mild" },
  { id: 3, name: "Common Cold", description: "Viral respiratory infection causing runny nose, sneezing, and congestion", possible_conditions: ["Rhinovirus infection", "Coronavirus", "RSV"], home_remedies: ["Rest and sleep", "Warm fluids", "Ginger honey lemon tea", "Steam inhalation", "Gargle with salt water"], recommended_medicines: ["Cetirizine", "Paracetamol", "Vitamin C"], when_to_see_doctor: "Symptoms lasting more than 10 days, high fever, difficulty breathing", severity: "mild" },
  { id: 4, name: "Sore Throat", description: "Pain, scratchiness or irritation in the throat", possible_conditions: ["Viral pharyngitis", "Strep throat", "Tonsillitis", "Acid reflux"], home_remedies: ["Gargle with warm salt water", "Honey and ginger tea", "Ice chips", "Turmeric milk"], recommended_medicines: ["Paracetamol", "Ibuprofen", "Amoxicillin (if bacterial)"], when_to_see_doctor: "Difficulty swallowing, high fever, white patches on tonsils, symptoms over a week", severity: "mild" },
  { id: 5, name: "Cough", description: "Reflex action to clear airways", possible_conditions: ["Common cold", "Asthma", "GERD", "Bronchitis", "Pneumonia", "TB"], home_remedies: ["Honey and warm water", "Steam inhalation", "Ginger turmeric tea", "Elevate head while sleeping"], recommended_medicines: ["Salbutamol (asthma)", "Amoxicillin (bacterial)"], when_to_see_doctor: "Coughing blood, persistent >3 weeks, chest pain", severity: "mild" },
  { id: 6, name: "Nausea", description: "Feeling of discomfort with urge to vomit", possible_conditions: ["Gastroenteritis", "Pregnancy", "Motion sickness", "Food poisoning"], home_remedies: ["Ginger tea", "Peppermint tea", "Small bland meals", "Deep breathing", "Cold compress on neck"], recommended_medicines: ["Metoclopramide", "Ondansetron", "Promethazine"], when_to_see_doctor: "Severe or persistent nausea, unable to keep fluids down", severity: "mild" },
  { id: 7, name: "Vomiting", description: "Forceful expulsion of stomach contents", possible_conditions: ["Gastroenteritis", "Food poisoning", "Pregnancy", "Head injury"], home_remedies: ["Clear fluids in small amounts", "Ginger tea", "Rest", "BRAT diet when able"], recommended_medicines: ["ORS", "Ondansetron", "Metoclopramide"], when_to_see_doctor: "Blood in vomit, >24 hours, signs of dehydration", severity: "moderate" },
  { id: 8, name: "Diarrhea", description: "Loose watery stools >3 times per day", possible_conditions: ["Gastroenteritis", "Food poisoning", "IBS", "Cholera"], home_remedies: ["ORS for rehydration", "BRAT diet", "Rice water", "Yogurt with probiotics"], recommended_medicines: ["ORS", "Loperamide", "Metronidazole (infective)", "Zinc"], when_to_see_doctor: "Blood in stool, severe dehydration, fever, >2 days", severity: "moderate" },
  { id: 9, name: "Stomach Ache", description: "Pain or discomfort in the abdominal region", possible_conditions: ["Gastritis", "Peptic ulcer", "IBS", "Appendicitis", "Gas/bloating"], home_remedies: ["Warm compress", "Ginger tea", "Peppermint tea", "Chamomile tea"], recommended_medicines: ["Omeprazole", "Metoclopramide", "Antacids"], when_to_see_doctor: "Severe persistent pain, pain with fever, blood in stool", severity: "mild" },
  { id: 10, name: "Back Pain", description: "Pain in the lumbar, thoracic, or cervical spine", possible_conditions: ["Muscle strain", "Herniated disc", "Kidney stones", "Sciatica"], home_remedies: ["Cold compress first 48h then heat", "Gentle stretching", "Massage with warm oil", "Good posture"], recommended_medicines: ["Ibuprofen", "Diclofenac", "Paracetamol"], when_to_see_doctor: "Pain with numbness/weakness, after injury, bowel/bladder changes", severity: "moderate" },
  { id: 11, name: "Joint Pain", description: "Pain, stiffness, or swelling in joints", possible_conditions: ["Osteoarthritis", "Rheumatoid arthritis", "Gout", "Viral arthritis"], home_remedies: ["Rest joint", "Ice for acute, heat for chronic", "Turmeric ginger tea", "Epsom salt bath"], recommended_medicines: ["Ibuprofen", "Diclofenac", "Prednisolone (severe)", "Calcium + Vitamin D"], when_to_see_doctor: "Severe swelling, redness, deformity, inability to move", severity: "moderate" },
  { id: 12, name: "Skin Rash", description: "Change in skin color, texture, or appearance", possible_conditions: ["Allergic reaction", "Eczema", "Psoriasis", "Contact dermatitis"], home_remedies: ["Cool compress", "Aloe vera gel", "Oatmeal bath", "Avoid scratching", "Coconut oil"], recommended_medicines: ["Cetirizine", "Loratadine", "Clotrimazole (fungal)", "Hydrocortisone cream"], when_to_see_doctor: "Spreading rash, with fever, difficulty breathing", severity: "mild" },
  { id: 13, name: "Allergy", description: "Immune system reaction to a foreign substance", possible_conditions: ["Seasonal allergy", "Food allergy", "Drug allergy", "Contact allergy"], home_remedies: ["Avoid triggers", "Saline nasal rinse", "Local honey", "Quercetin-rich foods"], recommended_medicines: ["Cetirizine", "Loratadine", "Promethazine", "Prednisolone (severe)"], when_to_see_doctor: "Anaphylaxis symptoms, difficulty breathing, severe reactions", severity: "moderate" },
  { id: 14, name: "High Blood Pressure", description: "Blood pressure consistently above 140/90 mmHg", possible_conditions: ["Essential hypertension", "Kidney disease", "Hormonal disorders"], home_remedies: ["DASH diet", "Regular exercise", "Reduce sodium", "Limit alcohol", "Meditation", "Garlic"], recommended_medicines: ["Amlodipine", "Lisinopril", "Losartan", "Atenolol", "Furosemide"], when_to_see_doctor: "BP above 180/110, headache with vision changes, chest pain", severity: "high" },
  { id: 15, name: "Diabetes", description: "Elevated blood glucose due to insufficient insulin or insulin resistance", possible_conditions: ["Type 1 diabetes", "Type 2 diabetes", "Gestational diabetes", "Pre-diabetes"], home_remedies: ["Karela juice", "Fenugreek seeds", "Cinnamon", "Regular exercise", "Low glycemic diet"], recommended_medicines: ["Metformin", "Glibenclamide", "Insulin"], when_to_see_doctor: "Blood sugar above 300 mg/dL, symptoms of DKA", severity: "high" },
  { id: 16, name: "Chest Pain", description: "Pain or discomfort in the chest area", possible_conditions: ["Angina", "Heart attack", "GERD", "Pleuritis", "Anxiety"], home_remedies: ["Sit upright and stay calm", "Antacid if acid reflux suspected"], recommended_medicines: ["Aspirin (emergency)", "Omeprazole (GERD-related)"], when_to_see_doctor: "IMMEDIATELY - always evaluated urgently", severity: "critical" },
  { id: 17, name: "Shortness of Breath", description: "Difficulty breathing or unable to get enough air", possible_conditions: ["Asthma", "COPD", "Heart failure", "Pneumonia", "Anemia", "COVID-19"], home_remedies: ["Pursed lip breathing", "Sit upright", "Breathing exercises", "Calm environment"], recommended_medicines: ["Salbutamol (inhaler)", "Montelukast", "Theophylline"], when_to_see_doctor: "Severe, at rest, with chest pain - EMERGENCY", severity: "critical" },
  { id: 18, name: "Dizziness", description: "Lightheadedness or spinning sensation", possible_conditions: ["Vertigo", "Dehydration", "Low blood pressure", "Anemia", "Inner ear disorder"], home_remedies: ["Sit or lie down immediately", "Drink water", "Slow position changes", "Ginger tea"], recommended_medicines: ["Betahistine", "Promethazine", "Meclizine"], when_to_see_doctor: "Sudden severe dizziness with headache/weakness - possible stroke", severity: "moderate" },
  { id: 19, name: "Fatigue", description: "Persistent tiredness that doesn't improve with rest", possible_conditions: ["Anemia", "Thyroid disorder", "Diabetes", "Depression", "Sleep disorder"], home_remedies: ["Regular sleep schedule", "Iron-rich foods", "Ashwagandha", "Moderate exercise", "Stay hydrated"], recommended_medicines: ["Ferrous Sulfate (if anemic)", "Multivitamins", "Vitamin D3"], when_to_see_doctor: "Persistent >2 weeks, with weight loss or fever", severity: "mild" },
  { id: 20, name: "Insomnia", description: "Difficulty falling or staying asleep", possible_conditions: ["Primary insomnia", "Anxiety", "Depression", "Sleep apnea"], home_remedies: ["Consistent sleep schedule", "Limit screens before bed", "Chamomile tea", "Warm bath"], recommended_medicines: ["Diazepam (short-term)", "Melatonin", "Promethazine"], when_to_see_doctor: "Affecting daily function for >3 weeks", severity: "moderate" },
  { id: 21, name: "Anxiety", description: "Excessive worry or fear affecting daily life", possible_conditions: ["Generalized anxiety", "Panic disorder", "PTSD", "Thyroid disorder"], home_remedies: ["Deep breathing and mindfulness", "Regular exercise", "Limit caffeine", "Journaling", "Social support"], recommended_medicines: ["Sertraline", "Fluoxetine", "Diazepam (short-term)", "Propranolol"], when_to_see_doctor: "Interfering with daily activities, panic attacks", severity: "moderate" },
  { id: 22, name: "Depression", description: "Persistent sadness, loss of interest, and hopelessness", possible_conditions: ["Major depressive disorder", "Bipolar disorder", "Postpartum depression"], home_remedies: ["Regular exercise", "Social connection", "Sunlight exposure", "Omega-3 foods", "Mindfulness"], recommended_medicines: ["Sertraline", "Fluoxetine"], when_to_see_doctor: "Suicidal thoughts, inability to function, severe symptoms >2 weeks", severity: "high" },
  { id: 23, name: "Urinary Issues", description: "Problems with urination including pain, frequency, or difficulty", possible_conditions: ["UTI", "Kidney infection", "Kidney stones", "Prostate issues"], home_remedies: ["Drink plenty of water", "Cranberry juice", "Avoid irritants", "Warm compress"], recommended_medicines: ["Ciprofloxacin (UTI)", "Amoxicillin (mild UTI)"], when_to_see_doctor: "Blood in urine, fever, inability to urinate", severity: "moderate" },
  { id: 24, name: "Migraine", description: "Severe throbbing headache with nausea and light sensitivity", possible_conditions: ["Migraine without aura", "Migraine with aura", "Chronic migraine"], home_remedies: ["Dark quiet room", "Cold compress", "Ginger tea", "Peppermint oil on temples"], recommended_medicines: ["Paracetamol", "Ibuprofen", "Propranolol (prevention)"], when_to_see_doctor: "First/worst headache ever, with neurological symptoms", severity: "moderate" },
  { id: 25, name: "Acid Reflux", description: "Burning sensation due to stomach acid backing up", possible_conditions: ["GERD", "Hiatal hernia", "Peptic ulcer", "H. pylori"], home_remedies: ["Smaller meals", "Don't lie down after eating", "Elevate head of bed", "Ginger tea", "Avoid trigger foods"], recommended_medicines: ["Omeprazole", "Pantoprazole", "Ranitidine", "Antacids"], when_to_see_doctor: "Symptoms >twice a week, difficulty swallowing, weight loss", severity: "moderate" },
  { id: 26, name: "Constipation", description: "Infrequent or difficult bowel movements", possible_conditions: ["Poor diet", "Dehydration", "IBS", "Hypothyroidism"], home_remedies: ["Increase fiber", "Drink 8+ glasses water", "Regular exercise", "Prunes", "Warm lemon water", "Isabgol"], recommended_medicines: ["Lactulose", "Bisacodyl", "Isabgol", "Senna"], when_to_see_doctor: "Lasting >3 weeks, blood in stool, severe abdominal pain", severity: "mild" },
  { id: 27, name: "Menstrual Pain", description: "Cramping pain during menstruation", possible_conditions: ["Primary dysmenorrhea", "Endometriosis", "Fibroids", "PCOS"], home_remedies: ["Heat pad on lower abdomen", "Ginger tea", "Exercise and yoga", "Chamomile tea"], recommended_medicines: ["Ibuprofen", "Diclofenac", "Mefenamic acid"], when_to_see_doctor: "Pain not relieved by OTC medicines, increasingly severe", severity: "moderate" },
  { id: 28, name: "Muscle Cramps", description: "Sudden involuntary muscle contractions", possible_conditions: ["Electrolyte imbalance", "Dehydration", "Poor circulation"], home_remedies: ["Stretch affected muscle", "Massage", "Heat or cold therapy", "Banana for potassium", "Stay hydrated"], recommended_medicines: ["ORS (electrolytes)", "Magnesium supplements"], when_to_see_doctor: "Frequent severe cramps, associated weakness", severity: "mild" },
  { id: 29, name: "Toothache", description: "Pain in or around a tooth", possible_conditions: ["Dental caries", "Abscess", "Gum disease", "Cracked tooth"], home_remedies: ["Clove oil", "Salt water rinse", "Cold compress on cheek", "Garlic paste"], recommended_medicines: ["Ibuprofen", "Paracetamol", "Amoxicillin (if abscess)"], when_to_see_doctor: "Severe pain, swelling of face/jaw, fever, pus drainage", severity: "moderate" },
  { id: 30, name: "Arthritis", description: "Inflammation and stiffness of joints", possible_conditions: ["Osteoarthritis", "Rheumatoid arthritis", "Gout", "Psoriatic arthritis"], home_remedies: ["Low-impact exercise", "Weight management", "Hot/cold therapy", "Turmeric", "Fish oil"], recommended_medicines: ["Ibuprofen", "Diclofenac", "Prednisolone", "Calcium + Vitamin D"], when_to_see_doctor: "Rapidly worsening, new joints affected, fever with joint pain", severity: "moderate" },
];

export const interactions = [
  { id: 1, drug1: "Warfarin", drug2: "Aspirin", severity: "MAJOR", description: "Significantly increases bleeding risk. Both inhibit platelet function.", management: "Avoid if possible. If needed, use minimum doses with close INR monitoring.", mechanism: "Pharmacodynamic synergy" },
  { id: 2, drug1: "Metformin", drug2: "Alcohol", severity: "MAJOR", description: "Increases risk of lactic acidosis - rare but potentially fatal.", management: "Avoid excessive alcohol during metformin treatment.", mechanism: "Both inhibit hepatic gluconeogenesis" },
  { id: 3, drug1: "Simvastatin", drug2: "Clarithromycin", severity: "MAJOR", description: "Clarithromycin inhibits CYP3A4, dramatically increasing simvastatin levels causing rhabdomyolysis.", management: "Stop simvastatin during clarithromycin. Use pravastatin instead.", mechanism: "CYP3A4 inhibition" },
  { id: 4, drug1: "Atenolol", drug2: "Verapamil", severity: "MAJOR", description: "Both slow heart rate. Can cause complete heart block or cardiac arrest.", management: "Generally avoid combination. Requires cardiac monitoring.", mechanism: "Pharmacodynamic synergy on cardiac conduction" },
  { id: 5, drug1: "Fluoxetine", drug2: "Tramadol", severity: "MAJOR", description: "Can cause serotonin syndrome - agitation, fever, rapid heart rate, seizures.", management: "Avoid combination. Report agitation, tremor, or fever immediately.", mechanism: "Both increase serotonergic activity" },
  { id: 6, drug1: "Diazepam", drug2: "Alcohol", severity: "MAJOR", description: "Both CNS depressants. Causes excessive sedation and respiratory depression - potentially fatal.", management: "Strictly avoid alcohol during benzodiazepine treatment.", mechanism: "Additive CNS depression (GABA enhancement)" },
  { id: 7, drug1: "Warfarin", drug2: "Fluconazole", severity: "MAJOR", description: "Fluconazole inhibits CYP2C9, doubling/tripling INR causing serious bleeding.", management: "Reduce warfarin dose 50%. Monitor INR closely.", mechanism: "CYP2C9 inhibition" },
  { id: 8, drug1: "Ibuprofen", drug2: "Warfarin", severity: "MODERATE", description: "NSAIDs increase anticoagulant effect and cause GI bleeding.", management: "Use paracetamol for pain instead. Monitor INR if unavoidable.", mechanism: "Platelet inhibition plus CYP2C9 inhibition" },
  { id: 9, drug1: "Ciprofloxacin", drug2: "Antacids", severity: "MODERATE", description: "Antacids significantly reduce ciprofloxacin absorption, reducing effectiveness.", management: "Take ciprofloxacin 2h before or 6h after antacids.", mechanism: "Chelation reduces drug absorption" },
  { id: 10, drug1: "Clopidogrel", drug2: "Omeprazole", severity: "MODERATE", description: "Omeprazole reduces conversion of clopidogrel to active form, reducing antiplatelet effectiveness.", management: "Use pantoprazole or famotidine as alternatives.", mechanism: "CYP2C19 inhibition reduces bioactivation" },
  { id: 11, drug1: "Prednisolone", drug2: "NSAIDs", severity: "MODERATE", description: "Significantly increases risk of GI ulceration and bleeding.", management: "Avoid combination or add gastroprotection (PPI).", mechanism: "Additive impairment of gastric mucosal defense" },
  { id: 12, drug1: "Digoxin", drug2: "Amiodarone", severity: "MAJOR", description: "Amiodarone increases digoxin levels 70-100% causing serious arrhythmias.", management: "Reduce digoxin dose 50%. Monitor levels and ECG.", mechanism: "Reduced renal clearance and volume of distribution" },
  { id: 13, drug1: "Beta-blockers", drug2: "Insulin", severity: "MODERATE", description: "Beta-blockers mask hypoglycemia symptoms (tremor, palpitations).", management: "Monitor blood glucose more carefully. Use cardioselective beta-blockers.", mechanism: "Beta-blockade masks adrenergic symptoms" },
  { id: 14, drug1: "ACE inhibitors", drug2: "Potassium", severity: "MODERATE", description: "Both increase potassium retention. Risk of dangerous hyperkalemia.", management: "Monitor serum potassium. Avoid supplements unless genuinely low.", mechanism: "Additive potassium retention" },
  { id: 15, drug1: "Carbamazepine", drug2: "Oral contraceptives", severity: "MODERATE", description: "Carbamazepine reduces contraceptive hormone levels by 50%, reducing effectiveness.", management: "Use barrier methods or higher dose/non-oral contraceptives.", mechanism: "CYP3A4 induction accelerates contraceptive metabolism" },
];
